package http

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/omekov/sosedi-group/internal/counter"
	counterHTTP "github.com/omekov/sosedi-group/internal/counter/delivery/http"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

type Handler struct {
	counterService *counter.Service
}

func NewHandler(counterService *counter.Service) *Handler {
	return &Handler{
		counterService,
	}
}

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func (h *Handler) Init() *echo.Echo {
	router := echo.New()
	router.Use(middleware.Logger())
	router.Use(middleware.Recover())
	router.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{http.MethodOptions, http.MethodGet, http.MethodHead, http.MethodPut, http.MethodPatch, http.MethodPost, http.MethodDelete},
	}))

	router.GET("/swagger/*", echoSwagger.WrapHandler)
	router.GET("/ping", func(c echo.Context) error {
		return c.JSON(http.StatusOK, nil)
	})

	handlerV1 := counterHTTP.NewHandler(h.counterService)
	counterGroup := router.Group("/rest")
	{
		handlerV1.Init(counterGroup)
	}

	return router
}
