// Code generated by MockGen. DO NOT EDIT.
// Source: internal/hasher/service.go

// Package mock_hasher is a generated GoMock package.
package mock_hasher

import (
	gomock "github.com/golang/mock/gomock"
)

// MockHasherService is a mock of HasherService interface.
type MockHasherService struct {
	ctrl     *gomock.Controller
	recorder *MockHasherServiceMockRecorder
}

// MockHasherServiceMockRecorder is the mock recorder for MockHasherService.
type MockHasherServiceMockRecorder struct {
	mock *MockHasherService
}

// NewMockHasherService creates a new mock instance.
func NewMockHasherService(ctrl *gomock.Controller) *MockHasherService {
	mock := &MockHasherService{ctrl: ctrl}
	mock.recorder = &MockHasherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasherService) EXPECT() *MockHasherServiceMockRecorder {
	return m.recorder
}
