basePath: /
definitions:
  http.CheckRequest:
    properties:
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for Sosedi Group API
  title: Sosedi Group API
  version: "1.0"
paths:
  /rest/counter/add/{num}:
    post:
      description: Redis increment
      parameters:
      - description: Counter number
        in: path
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Add (increment)
      tags:
      - counter
  /rest/counter/sub/{num}:
    post:
      description: Redis decrement
      parameters:
      - description: Counter number
        in: path
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Sub (decrement)
      tags:
      - counter
  /rest/counter/val:
    get:
      description: Redis get num
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Val
      tags:
      - counter
  /rest/email/check:
    post:
      description: Email Check
      parameters:
      - description: CheckRequest
        in: body
        name: CheckRequest
        required: true
        schema:
          $ref: '#/definitions/http.CheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Email Check
      tags:
      - email
  /rest/email/iin:
    post:
      description: IIN Check
      parameters:
      - description: CheckRequest
        in: body
        name: CheckRequest
        required: true
        schema:
          $ref: '#/definitions/http.CheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: IIN Check
      tags:
      - email
swagger: "2.0"
