basePath: /
host: localhost:8080
info:
  contact: {}
  description: REST API for Sosedi Group API
  title: Sosedi Group API
  version: "1.0"
paths:
  /rest/counter/add/{num}:
    post:
      description: Redis increment
      parameters:
      - description: Counter number
        in: path
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Add (increment)
      tags:
      - counter
  /rest/counter/sub/{num}:
    post:
      description: Redis decrement
      parameters:
      - description: Counter number
        in: path
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Sub (decrement)
      tags:
      - counter
  /rest/counter/val:
    get:
      description: Redis get num
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Counter Val
      tags:
      - counter
swagger: "2.0"
